services:
  Velox\MailSendVx\Controller\Admin\ConfigurationController:
    public: true
    arguments:
      - '@prestashop.module.mailsendvx.form.configuration_data_handler'
    tags:
      - { name: controller.service_arguments }

  Velox\MailSendVx\Controller\Admin\TemplatesController:
    public: true
    arguments:
      - '@prestashop.module.mailsendvx.service.template_admin'
      - '@prestashop.module.mailsendvx.grid.factory.templates'
      - '@prestashop.module.mailsendvx.grid.definition.factory.templates'
      - '@prestashop.bundle.grid.response_builder'
    tags:
      - { name: controller.service_arguments }

  Velox\MailSendVx\Controller\Admin\FlowsController:
    public: true
    arguments:
      - '@prestashop.module.mailsendvx.service.flow_admin'
      - '@prestashop.module.mailsendvx.grid.factory.queue'
      - '@prestashop.module.mailsendvx.grid.definition.factory.queue'
      - '@prestashop.bundle.grid.response_builder'
    tags:
      - { name: controller.service_arguments }

  Velox\MailSendVx\Controller\Admin\WrappersController:
    public: true
    arguments:
      - '@prestashop.module.mailsendvx.service.wrapper_manager'
      - '@prestashop.module.mailsendvx.service.template_content'
      - '@prestashop.module.mailsendvx.service.template_admin'
    tags:
      - { name: controller.service_arguments }

  Velox\MailSendVx\Controller\Admin\DocumentationController:
    public: true
    arguments:
      - '@prestashop.module.mailsendvx.service.template_admin'
      - '@prestashop.module.mailsendvx.service.fixture_generator'
    tags:
      - { name: controller.service_arguments }

  Velox\MailSendVx\Controller\Admin\DashboardController:
    public: true
    arguments:
      - '@prestashop.module.mailsendvx.service.dashboard_view'
      - '@prestashop.module.mailsendvx.grid.factory.events'
      - '@prestashop.module.mailsendvx.grid.factory.logs'
      - '@prestashop.module.mailsendvx.grid.definition.factory.events'
      - '@prestashop.module.mailsendvx.grid.definition.factory.logs'
      - '@prestashop.bundle.grid.response_builder'
    tags:
      - { name: controller.service_arguments }
