mailsendvx_configuration:
  path: /mailsendvx/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Velox\MailSendVx\Controller\Admin\ConfigurationController::indexAction'
    _legacy_controller: AdminMailsendvxConfigure
    _legacy_link: AdminMailsendvxConfigure

mailsendvx_templates:
  path: /mailsendvx/templates
  methods: [GET, POST]
  defaults:
    _controller: 'Velox\MailSendVx\Controller\Admin\TemplatesController::indexAction'
    _legacy_controller: AdminMailsendvxTemplates
    _legacy_link: AdminMailsendvxTemplates

mailsendvx_flows:
  path: /mailsendvx/flows
  methods: [GET, POST]
  defaults:
    _controller: 'Velox\MailSendVx\Controller\Admin\FlowsController::indexAction'
    _legacy_controller: AdminMailsendvxFlows
    _legacy_link: AdminMailsendvxFlows

mailsendvx_wrappers:
  path: /mailsendvx/wrappers
  methods: [GET, POST]
  defaults:
    _controller: 'Velox\MailSendVx\Controller\Admin\WrappersController::indexAction'
    _legacy_controller: AdminMailsendvxWrappers
    _legacy_link: AdminMailsendvxWrappers

mailsendvx_documentation:
  path: /mailsendvx/documentation
  methods: [GET]
  defaults:
    _controller: 'Velox\MailSendVx\Controller\Admin\DocumentationController::indexAction'
    _legacy_controller: AdminMailsendvxDocumentation
    _legacy_link: AdminMailsendvxDocumentation

mailsendvx_template_delete:
  path: /mailsendvx/templates/{idTemplate}/delete
  methods: [POST]
  defaults:
    _controller: 'Velox\MailSendVx\Controller\Admin\TemplatesController::deleteAction'
    _legacy_controller: AdminMailsendvxTemplates
  requirements:
    idTemplate: \d+

mailsendvx_template_test:
  path: /mailsendvx/templates/{idTemplate}/test
  methods: [POST]
  defaults:
    _controller: 'Velox\MailSendVx\Controller\Admin\TemplatesController::sendTestAction'
    _legacy_controller: AdminMailsendvxTemplates
  requirements:
    idTemplate: \d+

mailsendvx_dashboard:
  path: /mailsendvx/dashboard
  methods: [GET]
  defaults:
    _controller: 'Velox\MailSendVx\Controller\Admin\DashboardController::indexAction'
    _legacy_controller: AdminMailsendvxDashboard
    _legacy_link: AdminMailsendvxDashboard

mailsendvx_queue_cancel:
  path: /mailsendvx/queue/{idQueue}/cancel
  methods: [POST]
  defaults:
    _controller: 'Velox\MailSendVx\Controller\Admin\FlowsController::cancelQueueJobAction'
    _legacy_controller: AdminMailsendvxFlows
  requirements:
    idQueue: \d+
