<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1b53ed48c7852080a52cb9b2ec45cd96
{
    public static $prefixLengthsPsr4 = array (
        'V' => 
        array (
            'Velox\\MailSendVx\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Velox\\MailSendVx\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1b53ed48c7852080a52cb9b2ec45cd96::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1b53ed48c7852080a52cb9b2ec45cd96::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1b53ed48c7852080a52cb9b2ec45cd96::$classMap;

        }, null, ClassLoader::class);
    }
}
